### ISSUE TITLE
Public calendars

### ISSUE THREAD

**Issue by luiscruz** [davidgundry/jekyll-google-calendar#2]
Hi, can I use this plugin for public calendars, without providing a personal "key_file: PATH-TO-YOUR-GOOGLE-SERVICE-ACCOUNT-KEY.json"?

Thanks,
Luís

**Comment by davidgundry** [comment]
Sorry for not seeing this earlier. No. Google requires you to have a Google service account in order to use their API, whether the calendars are public or private. I think you can get a free account which has usage limits, though it's been a little while since I've done this.

If you visit [https://console.developers.google.com/](https://console.developers.google.com/) and sign in with a Google account, you should be able to configure various Google APIs from there and download service account keys.

**Comment by luiscruz** [comment]
Thanks, @davidgundry
